export const productCreate = {
    POST_PRODUCT_API_REQUEST: "POST_PRODUCT_API_REQUEST",
    POST_PRODUCT_API_SUCCESS: "POST_PRODUCT_API_SUCCESS",
    POST_PRODUCT_API_FAILURE: "POST_PRODUCT_API_FAILURE",
};