export const postStockAPI = {
    POST_STOCK_API_REQUEST: "POST_STOCK_API_REQUEST",
    POST_STOCK_API_SUCCESS: "POST_STOCK_API_SUCCESS",
    POST_STOCK_API_FAILURE: "POST_STOCK_API_FAILURE",
};
export const getStockAPI = {
    GET_STOCK_API_REQUEST: "GET_STOCK_API_REQUEST",
    GET_STOCK_API_SUCCESS: "GET_STOCK_API_SUCCESS",
    GET_STOCK_API_FAILURE: "GET_STOCK_API_FAILURE",
};

export const postOrderAPI = {
    POST_ORDER_API_REQUEST: "POST_ORDER_API_REQUEST",
    POST_ORDER_API_SUCCESS: "POST_ORDER_API_SUCCESS:",
    POST_ORDER_API_FAILURE: "POST_ORDER_API_FAILURE",
};