export const postAPI = {
    POST_API_REQUEST: "POST_API_REQUEST",
    POST_API_SUCCESS: "POST_API_SUCCESS",
    POST_API_FAILURE: "POST_API_FAILURE",
};

export const getAPI = {
    GET_API_REQUEST: "GET_API_REQUEST",
    GET_API_SUCCESS: "GET_API_SUCCESS",
    GET_API_FAILURE: "GET_API_FAILURE",
};

export const deleteAPI = {
    DELETE_API_REQUEST: "DELETE_API_REQUEST",
    DELETE_API_SUCCESS: "DELETE_API_SUCCESS",
    DELETE_API_FAILURE: "DELETE_API_FAILURE",
};

export const updateAPI = {
    UPDATE_API_REQUEST: "UPDATE_API_REQUEST",
    UPDATE_API_SUCCESS: "UPDATE_API_SUCCESS",
    UPDATE_API_FAILURE: "UPDATE_API_FAILURE",
};


export const userPostAPI = {
    POST_USER_API_REQUEST: "POST_USER_API_REQUEST",
    POST_USER_API_SUCCESS: "POST_USER_API_SUCCESS",
    POST_USER_API_FAILURE: "POST_USER_API_FAILURE",
};


export const userGetAPI = {
    GET_USER_API_REQUEST: "GET_USER_API_REQUEST",
    GET_USER_API_SUCCESS: "GET_USER_API_SUCCESS",
    GET_USER_API_FAILURE: "GET_USER_API_FAILURE",
};

export const userAllGetAPI = {
    GET_ALLUSER_API_REQUEST: "GET_ALLUSER_API_REQUEST",
    GET_ALLUSER_API_SUCCESS: "GET_ALLUSER_API_SUCCESS",
    GET_ALLUSER_API_FAILURE: "GET_ALLUSER_API_FAILURE",
};

export const userupdateAPI = {
    UPDATE_USER_API_REQUEST: "UPDATE_USER_API_REQUEST",
    UPDATE_USER_API_SUCCESS: "UPDATE_USER_API_SUCCESS",
    UPDATE_USER_API_FAILURE: "UPDATE_USER_API_FAILURE",
};

export const userdeleteAPI = {
    DELETE_USER_API_REQUEST: "DELETE_USER_API_REQUEST",
    DELETE_USER_API_SUCCESS: "DELETE_USER_API_SUCCESS",
    DELETE_USER_API_FAILURE: "DELETE_USER_API_FAILURE",
};