export const userPostAPI = {
    USER_POST_API_REQUEST: "USER_POST_API_REQUEST",
    USER_POST_API_SUCCESS: "USER_POST_API_SUCCESS",
    USER_POST_API_FAILURE: "USER_POST_API_FAILURE",
};

export const userUpdateAPI = {
    USER_UPDATE_API_REQUEST: "USER_UPDATE_API_REQUEST",
    USER_UPDATE_API_SUCCESS: "USER_UPDATE_API_SUCCESS",
    USER_UPDATE_API_FAILURE: "USER_UPDATE_API_FAILURE",
};